create database http_sd;

\c http_sd

create table targets (
  id int primary key generated by default as identity,
  enabled boolean not null default true,
  job text not null,
  target text not null,
  labels jsonb
);

create view sd as
select
  jsonb_agg(target) as targets,
  merged_labels as labels
from (
  select
    target,
    (coalesce(labels, '{}'::jsonb) || jsonb_build_object('job', job)) as merged_labels
  from targets
  where enabled
)
group by merged_labels;

create role http_sd_public nologin;
grant select on targets, sd to http_sd_public;

create role http_sd_backend noinherit login password '';
grant http_sd_public to http_sd_backend;
